sudo: false
cache:
  directories:
    - $HOME/miniconda
    - $HOME/kaldi
  timeout: 1000
branches:
  only:
    - master
language: python
matrix:
  include:
    - python: 2.7
before_install:
  - # Setup Python environment with BLAS libraries
  - export SKIP=1
  - function skip_rest { export SKIP=0; }
  - function skip { return $SKIP; }
  - ./install/install_conda.sh || skip_rest
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update -q --yes conda
  - conda install -q --yes python=$TRAVIS_PYTHON_VERSION gcc pip boost-python
  - (skip || ./install/install_kaldi_deps.sh) || skip_rest
  - skip || ./install/install_kaldi.sh || skip_rest
  - export KALDI_ROOT=$HOME/kaldi/
install:
  - skip || conda install --yes numpy
script:
  - skip || pip install . # Tests setup.py
  - skip || python -c "import kaldi_io"
